-- 역할 프리셋 기본 구성을 행으로 적재한다(2026-09-16) — 이제 기능모듈 화면에서 자리마다 켜고 끌 수 있다.
-- 코드(shared/rbac/presets.ts)의 값을 그대로 옮긴 것이고, 이 행이 하나도 없으면 코드 기본값이 쓰인다.
--
-- ⚠️ **없는 모듈은 건너뛴다.** 기능모듈 행은 시드(db/seed/feature_module.csv)가 넣는다 — 마이그레이션만 돌린
--    빈 DB(CI 검증)에는 아직 없어서 외래키에 걸렸다. 있는 것만 넣고, 나머지는 시드 뒤 화면에서 켠다.
INSERT INTO "access_control" ("subject_type", "subject_ref", "module_code", "enabled", "memo")
SELECT 'preset'::"SubjectType", v.ref, v.code, true, '프리셋 기본값 — 기능모듈 화면에서 고친다'
FROM (VALUES
  ('sales_mgr', 'addon.view'),
  ('sales_mgr', 'customer.view'),
  ('sales_mgr', 'doc.send.email'),
  ('sales_mgr', 'doc.send.sign'),
  ('sales_mgr', 'doc.view'),
  ('sales_mgr', 'notify.push'),
  ('sales_mgr', 'order.confirm'),
  ('sales_mgr', 'order.view'),
  ('sales_mgr', 'quote.confirm'),
  ('sales_mgr', 'quote.edit'),
  ('sales_mgr', 'stats.all'),
  ('sales_mgr', 'stats.own'),
  ('pm', 'addon.manage'),
  ('pm', 'basedata.dims'),
  ('pm', 'basedata.makerprice'),
  ('pm', 'basedata.optiondb'),
  ('pm', 'basedata.weights'),
  ('pm', 'checklist.manage'),
  ('pm', 'doc.view'),
  ('pm', 'notify.push'),
  ('pm', 'order.confirm'),
  ('pm', 'order.control'),
  ('pm', 'order.remove'),
  ('pm', 'order.view'),
  ('pm', 'quote.confirm'),
  ('pm', 'quote.edit'),
  ('pm', 'stats.all'),
  ('pm', 'stats.own'),
  ('prod_mgr', 'addon.manage'),
  ('prod_mgr', 'basedata.makerprice'),
  ('prod_mgr', 'checklist.manage'),
  ('prod_mgr', 'doc.view'),
  ('prod_mgr', 'notify.push'),
  ('prod_mgr', 'order.confirm'),
  ('prod_mgr', 'order.control'),
  ('prod_mgr', 'order.view'),
  ('prod_mgr', 'quote.confirm'),
  ('prod_mgr', 'quote.edit'),
  ('prod_mgr', 'stats.all'),
  ('prod_mgr', 'stats.own'),
  ('exec', 'addon.view'),
  ('exec', 'doc.view'),
  ('exec', 'notify.push'),
  ('exec', 'order.view'),
  ('exec', 'quote.confirm'),
  ('exec', 'quote.edit'),
  ('exec', 'stats.all'),
  ('exec', 'stats.own'),
  ('master', 'account.manage'),
  ('master', 'addon.manage'),
  ('master', 'addon.view'),
  ('master', 'basedata.dims'),
  ('master', 'basedata.holiday'),
  ('master', 'basedata.makerprice'),
  ('master', 'basedata.manage'),
  ('master', 'basedata.optiondb'),
  ('master', 'basedata.weights'),
  ('master', 'checklist.manage'),
  ('master', 'customer.view'),
  ('master', 'doc.send.email'),
  ('master', 'doc.send.sign'),
  ('master', 'doc.view'),
  ('master', 'notify.assign'),
  ('master', 'notify.push'),
  ('master', 'order.confirm'),
  ('master', 'order.control'),
  ('master', 'order.remove'),
  ('master', 'order.view'),
  ('master', 'quote.confirm'),
  ('master', 'quote.create'),
  ('master', 'quote.delete'),
  ('master', 'quote.edit'),
  ('master', 'stats.all'),
  ('master', 'stats.own')
) AS v(ref, code)
WHERE EXISTS (SELECT 1 FROM "feature_module" f WHERE f."code" = v.code)
ON CONFLICT ("subject_type", "subject_ref", "module_code") DO NOTHING;
